In [30]:
x=int(input('enter num   '))
if x%5==0 & x%4==0:
    print(x,'divided by 4,5')
elif x%3==0 | x%6==0:
    print(x,'is  divisible by 3,6')
else:
    print('none')

enter num   24
24 is  divisible by 3,6


In [38]:
x='python'
if x>len(x) and x>2002:
      print('btwn 150-200')
elif x>400 or x>300:
      print(' anything')
else:
      print('nothing')

 anything


In [59]:
i=1
while i<10:
    i=i*4+2
    
    print(i)
else:
    print('python is superb')
    
    

6
26
python is superb


In [20]:
#l=[1,2,3,4,5,56,7,33]
for x in range(1,21):#range 1-40(2,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15)n-1
    if x%2==0:
        print(x)
    
else:
    print('for')
    

2
4
6
8
10
12
14
16
18
20
for


In [3]:
list=[1,2,3,4,5]
for i in list:
    print(i)

1
2
3
4
5


In [25]:
#ZIp FUNCTION
ages={
    'bh':24,
     'sa':25,
     'rb':45445,
     'num':33535
     }
zipped_1=zip(ages.values(),ages.keys())
print(sorted(zipped_1))

zipped_2=zip(ages.keys(),ages.values())
print(sorted(zipped_2))

[(24, 'bh'), (25, 'sa'), (33535, 'num'), (45445, 'rb')]
[('bh', 24), ('num', 33535), ('rb', 45445), ('sa', 25)]


In [21]:
for i in range(1,13,2):#dynamic
    if(i%5==0):
        print(i)
    else:
        print('nummbers')

nummbers
nummbers
5
nummbers
nummbers
nummbers


In [66]:
i=4
while i==True:
    print(i)
    i=i+1
if(i<=3):
    print('x')
else:
    print(i)
    

4


In [75]:
i=6
while i<=10:
    pass
    i=i+1
   
    print(i)
   
    
    

7
8
9
10
11


In [79]:
for i in range(1,20):
    if(i%2==0):
        print(i)
    else:
        pass

2
4
6
8
10
12
14
16
18


In [5]:
for i in range(5):
    if i==3:
        break
    print(i)

0
1
2


In [28]:
words=['i',' like',' python']#int123+str python
sen=''.join(words)
print(sen)

i like python


In [6]:
import numpy as np

lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]
arr=np.array([lst1,lst2,lst3])

In [7]:
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [8]:
arr.shape

(3, 5)

In [9]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [10]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [11]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [14]:
arr[1:4,2:-1]

array([[4, 5],
       [5, 6]])

In [4]:
arr1=[1,2,3,3,3,3,3,3]
arr1[2:]=400
print(arr1)


TypeError: can only assign an iterable

In [20]:
arr1

[1, 2, 3, 3, 45, 6, 6, 7, 88]

In [21]:
val=2
arr/2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [1. , 1.5, 2. , 2.5, 3. ],
       [1.5, 2. , 2.5, 3. , 3.5]])

In [28]:
arr=np.arange(0,10).reshape(5,2)
print(arr)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [29]:
import pandas as pd
import numpy as np

In [31]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['row1','row2','row3','row4','row5'],columns=['column1','column2','column3','column4'])

In [33]:
df.head()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [34]:
df.to_csv('test1.csv')

In [37]:
type(df.loc['row1'])

pandas.core.series.Series

In [38]:
df.iloc[0:4,0:2]

column1  column2
row1        0        1
row2        4        5
row3        8        9
row4       12       13

In [39]:
type(df.iloc[0:4,0:2])

pandas.core.frame.DataFrame

In [42]:
df.iloc[:,1:]

column2  column3  column4
row1        1        2        3
row2        5        6        7
row3        9       10       11
row4       13       14       15
row5       17       18       19

In [44]:
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [45]:
df.isnull().sum()

column1    0
column2    0
column3    0
column4    0
dtype: int64

In [49]:
df['column1'].value_counts()

12    1
4     1
16    1
8     1
0     1
Name: column1, dtype: int64

In [50]:
df['column1'].unique()

array([ 0,  4,  8, 12, 16], dtype=int64)

In [4]:
#functions

def fun(name):
    print('hello',name)
fun('bhaskar')

hello bhaskar


In [9]:
def fun1(x,y):
    print('addition',x+y)
fun1(3,2)

addition 5


In [ ]:
def fun12(a,b):
    a=int(input('enter number:'))
    b=int(input('enter number :'))
    print('sum',a+b)
fun12(23,44)

In [21]:
def add_sub_mul(x,y):
    c=x+y
    d=x-y
    z=x*y
    return c,d,z
result,result1,result2=add_sub_mul(4,5)
print(result,result1,result2)

9 -1 20


In [20]:
def funm(x,y):
    c=x+y
    d=x*y
    f=x-y
    return c,d,f
r,r1,r2=funm(5,6)
print(r,r2,r1)

11 -1 30


In [ ]:
def funm(x,y):
    c=x+y
    d=x*y
    f=x-y
    return c,d,f
funm(5,6)

In [37]:
def update(lst):
    
    print(id(lst))
    lst[1]=25
    
    #print(id(x))
    print("x",lst)
lst=[10,20,30]
print(id(lst))
update(lst)
print('a',lst)

1955427692296
1955427692296
x [10, 25, 30]
a [10, 25, 30]


In [42]:
def per(name,age):
    print(name)
    print(age)
per(name='bhaskar',age=28)

bhaskar
28


In [5]:
def sum(*b):
    c=1
    for i in b:
        c=c+i
    print(c)
sum(5,4,34,2)

46


In [27]:
def muul(*b):
    c=1
    for i in b:
        c=c-i
    print(c)
muul(32,22,43,56)

-152


In [52]:
def pers(name,**data):
    print(name)
    print(data)
pers('bhaskar',age=22,city='vizag',ph=873647364)

bhaskar
{'age': 22, 'city': 'vizag', 'ph': 873647364}


In [30]:
def prsnsn(nam,**age):
    print(nam)
    print(age)
prsnsn('rb',ages=25,city='vizag',ph=342545773456)

rb
{'ages': 25, 'city': 'vizag', 'ph': 342545773456}


In [2]:
def fun123(a,*b):
    print(a)
    print(b)
fun123(3,2,4,13,34)

3
(2, 4, 13, 34)


In [4]:
def fun1234(a,**b):
    print(a)
    print(b)
fun1234('sai',age=12,salary=23,phno=3,addr=4)

sai
{'age': 12, 'salary': 23, 'phno': 3, 'addr': 4}


In [6]:
def dig(name,**r):
    print(name)
    
    for i,j in r.items():
        print(i,j)
dig('sai',city='vizag',phn=92892,cmpny='ajh')

sai
city vizag
phn 92892
cmpny ajh


In [10]:
def f(*data):
   # print(name)
    c=0
    for i in data:
        c=c+i
        print(c)
f(2,3,4,5,45,6,8)

2
5
9
14
59
65
73


In [14]:
a=10
def som():
    global a
    a=15
    print(a)
som()
print(a)

15
15


In [15]:
[x for x in range(1,11)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [16]:
[x for x in range(1,11) if x%2==0]

[2, 4, 6, 8, 10]

In [17]:
 [x if x>2 else x+2 for x in range(1,11)]

[3, 4, 3, 4, 5, 6, 7, 8, 9, 10]

In [31]:
[x if x>3 else x*2 for x in range(2,21)]

[4, 6, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [18]:
n=[1,2,3,4,5,6,7]
[x*23 for x in n]

[23, 46, 69, 92, 115, 138, 161]

In [19]:
a=['hello','kdkd','djjd']
[x.upper() for x in a]

['HELLO', 'KDKD', 'DJJD']

In [24]:
str1='bhaskar1234'
[x for x in str1 if x.isalpha()]

['b', 'h', 'a', 's', 'k', 'a', 'r']

In [26]:
a=[1,2,3,4]
b=[2,3,4,5]
[x+y for x in a for y in b]

[3, 4, 5, 6, 4, 5, 6, 7, 5, 6, 7, 8, 6, 7, 8, 9]

In [27]:
str1='hello gud mng bhaskar'
str1.replace('gud','happy')

'hello happy mng bhaskar'

In [33]:
str2='drive on broad road'
str2[15:].replace('road','dk')

'dk'

In [36]:
def add(a,b):
    return a+b
add(55,88)

143

In [37]:
addi=lambda a,b:a*b
addi(55,88)

4840

In [1]:
n=[1,2,3,4]
[x*20 for x in n]

[20, 40, 60, 80]

In [3]:
str1='bhaskar123'
[x.upper() for x in str1]

['B', 'H', 'A', 'S', 'K', 'A', 'R', '1', '2', '3']

In [4]:
[x for x in str1 if x.isdigit()]

['1', '2', '3']

In [5]:
[x for x in str1 if x.isalpha()]

['b', 'h', 'a', 's', 'k', 'a', 'r']

In [9]:
def square(x):
    return x*x


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [10]:
[square(x) for x in range(1,11)]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [17]:
a=[1,2,3,4]
b=[2,3,4,5]
[x+y for x in a for y in b]
[a[i]+b[i] for i in range(0,1)]

[3]

In [25]:

a=lambda x,y:x*y

In [26]:
a(44,55)

2420

In [6]:
def even():
    return n%2==0
nums=[12,2,3,34,34,5,6,6,5,56]
evens=list(filter(even))
print(evens)

TypeError: filter expected 2 arguments, got 1

In [7]:
n=[1,2,3,4]
it=iter(n)
print(it.__next__())
print(next(it))
for i in n:
    print(i)

1
2
1
2
3
4


In [36]:
n=[1,12,1,13,14,144]
it=iter(n)
print(it.__next__())
print(next(it))
for x in n:
    print(x)

1
12
1
12
1
13
14
144


In [38]:
def fib(n):
    a=0
    b=1
    for i in range(2,n):
        c=a+b
        a=b
        b=a
        
        print(c)
fib(7)


1
2
2
2
2


In [39]:
def fact(n):
    if n==0:
        return 1
    return n*fact(n-1)
fact(6)

720

In [40]:
def func(number):
    def funmn(number):
        return number+1
    r=funmn(number)
    print(r)
func(6)

7


In [23]:
class python:
    def __init__(self,clas,objec):
        self.clas=clas
        self.objec=objec
    def oops(self):
            print('it is a versatile language', self.clas,self.objec)
py=python('bhaskar','34')
py1=python('sai 3','23')

py.oops()
py1.oops()

it is a versatile language bhaskar 34
it is a versatile language sai 3 23


In [43]:
class com:
    def __init__(self,clas,obj):
        self.clas=clas
        self.obj=obj
    def oops(self):
             print('it is good',self.clas,self.obj)
py=com('sai',3434)
py1=com('dfadf',23)

py.oops()
py1.oops()
        

it is good sai 3434
it is good dfadf 23


In [26]:
class python:
    # constructor
    def __init__(self,num,obj):
        # initializing instance variable
        self.num=num
        self.obj=obj

    # a method
    def oops(self):
        print(self.num,self.obj)


# creating object of the class. This invokes constructor
obj = python(100,'bhaskar')

# calling the instance method using the object obj
obj.oops()

100 bhaskar


In [27]:
class java:
    num=123
    def oops(self):
        print(self.num)
obj1=java()
obj1.oops()

123


In [2]:
def mul(a,b):
    return a*b
print(mul(2,3))
print(__name__)

6
__main__


In [9]:
def div(a,b):
    return a/b
def smart_div(func):
    def inner(a,b):
            if a<b:
                a,b=b,a
            return func(a,b)
    return inner
div=smart_div(div)
div(2,4)

2.0

In [11]:
def div1(a,b):
    return a/b
def smart_div1(func):
    def inner(a,b):
        if a<b:
            a,b=b,a
        return func(a,b)
    return inner
div1=smart_div1(div1)
div1(4,3)

1.3333333333333333

In [13]:
def x():
    n=1
    while n<=10:
        sq=n*n
    yield sq
    n=n+1
    
    
values=x()
for i in values:
    print(i)

KeyboardInterrupt: 

In [18]:
def x1():
    n=1
    while n<=10:
        sq=n*n
        yield sq
        n+=1
    
    
values=x1()
for i in values:
    print(i)

1
4
9
16
25
36
49
64
81
100


In [23]:
class A:
    def fet1(self):
        print('fet1 is working ')
    def fet2(self):
        print('fet2 is working')
class B():
    def fet3(self):
         print('fet3 is working ')
    def fet4(self):
        print('fet4 is working')
class C(A,B):
    def fet5(self):
        print('fet5 is working')
a=A()
b=B()
c=C()
a.fet1()
a.fet2()
b.fet3()
b.fet4()
c.fet1()

        

fet1 is working 
fet2 is working
fet3 is working 
fet4 is working
fet1 is working 


In [99]:
import random
list=[1,2,3,4,5,5,6]
random.shuffle(list)

print(list)

[4, 1, 3, 5, 6, 5, 2]


In [100]:
x='python is a lang'
x.split()

['python', 'is', 'a', 'lang']

In [111]:
st='bskar is good boy'
list(st)


TypeError: 'list' object is not callable

In [114]:
l='jai hind'
for i in l:
    if i=='a':
        pass
    #print('passed')
else:
    print('not passed')

not passed


In [115]:
import re
print(re.search(r"[0-9a-zA-Z.]+@[a-zA-Z]+\.(com|co\.in)$","micheal.pages@mp.com"))

<re.Match object; span=(0, 20), match='micheal.pages@mp.com'>


In [116]:
str1='my name is gavaskar'
str1.replace('gava','bha')

'my name is bhaskar'

In [123]:
str2='my name is rodies jhonty rodies'

str2.replace('rodies','roades')
str2[0:17]+str2[17:].replace('rodies','roades')

'my name is rodies jhonty roades'

In [163]:
import math
x=5/2
math.ceil(x)

3

In [166]:
x=math.sqrt(25)
math.ceil(x)

5

In [130]:
_*9

27

In [138]:
keys=['bh','as','ka','ra']
values=[1,2,3,4,5]
items=dict(zip(keys,values))
items

{'bh': 1, 'as': 2, 'ka': 3, 'ra': 4}

In [139]:
items['bh']='asa'
items

{'bh': 'asa', 'as': 2, 'ka': 3, 'ra': 4}

In [140]:
di={'bhas':23,'sald':232,'ljsd':['asd','ew'],'oowd':{'scne':346,'fgotmb':5688}}
di

{'bhas': 23,
 'sald': 232,
 'ljsd': ['asd', 'ew'],
 'oowd': {'scne': 346, 'fgotmb': 5688}}

In [148]:
di['ljsd'][1]

'ew'

In [150]:
di['oowd']['scne']

346

In [162]:
#list=[1,2,3,3,4,5]
for i in range(1,20,3):
    print(i*4)

4
16
28
40
52
64
76


In [170]:
x=eval(input('enter ch'))
print(x)

enter ch2+3*4-2
12


In [9]:
List={1,2,3,3,44,56,23}
odd=list(filter(lambda x:(x%3==0),List))
print (odd)

[3]


In [8]:
list1={1,2,3,4,5,6,7,8}
new=list(map(lambda x:x*3,list1))
print(new)

[3, 6, 9, 12, 15, 18, 21, 24]


In [15]:
#prime number
num=7
for i in range(2,num):
    if num%i==0:
        print(num,' prime')
    else:
        print(i,'not prime')

2 not prime
3 not prime
4 not prime
5 not prime
6 not prime


In [19]:
num=int(input('enter num:'))
if num>1:
    for i in range(2,num):
        if num%1==0:
            print(num,' prime')
            break
    else:
        print(num,'is prime')
else:
    print(num,'not prime')
        

enter num:23
23  prime
